FROM node:latest 
 
RUN apt-get update && \
    apt-get install -y  sudo && \
    apt-get install -y nano 

RUN useradd -m docker && echo "docker:docker" | chpasswd && adduser docker sudo 

WORKDIR /home/docker

EXPOSE 3000-3005:3000-3005

RUN npm install http-server -g && \
    npm install gulp -g && \
    npm install jshint -g && \
    npm install typescript -g && \
    npm install sails -g

USER docker
